apiVersion: v1
kind: Namespace
metadata:
  name: gitops-database-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-database-secret-operator-group
  namespace: gitops-database-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-database-secret
---
