apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-gitops-database-secret
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-database-secret/namespace
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-database-secret-ocp4.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
